name: CI

on:
  push:
    branches:
    - master

jobs:
  build_backend:
    runs-on: ubuntu-latest
    steps:
    - name: Test
    - run: dotnet test --no-restore --verbosity normal
    - uses: actions/checkout@v1
    - name: Build and deploy the Docker image
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        APP_NAME: ${{ 'energy-platform-backend' }}
      run: |
        cd .
        docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME
